=== EBIvariation/eva-sub-cli/eva_sub_cli/etc/eva_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "version": "1.0.0",
  "$id": "EVA_metadata_schema",
  "author": "EVA",
  "type": "object",
  "title": "EVA metadata schema",
  "description": "",
  "required": [
    "submitterDetails",
    "project",
    "sample",
    "analysis",
    "files"
  ],
  "properties": {
    "submitterDetails": {
      "type": "array",
      "description": "Contact details of the submitter",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "lastName",
          "firstName",
          "email",
          "laboratory",
          "centre"
        ],
        "properties": {
          "lastName": {
            "type": "string",
            "description": "Last name of the contact"
          },
          "firstName": {
            "type": "string",
            "description": "First name of the contact"
          },
          "telephone": {
            "type": "string",
            "description": "Contact's phone number"
          },
          "email": {
            "type": "string",
            "format": "email",
            "description": "Contact's Email",
            "examples": [
              "user@domain.com"
            ]
          },
          "laboratory": {
            "description": "Name of the laboratory or department of the contact",
            "type": "string"
          },
          "centre": {
            "description": "Name of the Centre, company or institute the contact belongs to",
            "type": "string"
          },
          "address": {
            "description": "Address of the Centre, company or institute the contact belongs to",
            "type": "string"
          }
        }
      }
    },
    "statements": {
      "type": "array",
      "description": "Submitter acknowledgements of various EVA data statements",
      "items": {
        "type": "object",
        "required": ["acknowledgement", "statement"],
        "additionalProperties": false,
        "properties": {
          "acknowledgement": {
            "type": "boolean",
            "description": "Whether the submitter confirmed this statement"
          },
          "statement": {
            "type": "string",
            "description": "Full text of the statement as presented to the submitter"
          }
        }
      }
    },
    "project": {
      "type": "object",
      "if": {
        "required": [
          "projectAccession"
        ]
      },
      "then": {
        "properties": {
          "projectAccession": {
            "$ref": "#/definitions/projectAccession"
          }
        }
      },
      "else": {
        "description": "General information about the Project",
        "required": [
          "title",
          "description",
          "taxId",
          "centre"
        ],
        "properties": {
          "title": {
            "type": "string",
            "description": "Title of the project",
            "minLength": 20,
            "maxLength": 250
          },
          "description": {
            "type": "string",
            "description": "Description of the project",
            "minLength": 20,
            "maxLength": 4000
          },
          "centre": {
            "type": "string",
            "description": "Centre, institute or company submitting the project"
          },
          "taxId": {
            "type": "number",
            "description": "Taxonomy ID of the species associated with the project (found here: http://www.ncbi.nlm.nih.gov/taxonomy)"
          },
          "publications": {
            "type": "array",
            "description": "Publications associated with the project, each given as <database>:<identifier>",
            "items": {
              "type": "string",
              "pattern": "^[^:,]+?:[^:,]+?$",
              "examples": [
                "DOI:10.1093/nar/gkw1121",
                "PMID:24565421"
              ]
            }
          },
          "parentProject": {
            "$ref": "#/definitions/projectAccession"
          },
          "childProjects": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/projectAccession"
            }
          },
          "peerProjects": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/projectAccession"
            }
          },
          "links": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "holdDate": {
            "type": "string",
            "format": "date",
            "examples": [
              "2018-11-13"
            ]
          }
        }
      }
    },
    "analysis": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "analysisTitle",
          "analysisAlias",
          "description",
          "experimentType",
          "referenceGenome"
        ],
        "properties": {
          "analysisTitle": {
            "type": "string",
            "description": "Title of the analysis"
          },
          "analysisAlias": {
            "type": "string",
            "description": "Shortened identifier for the analysis"
          },
          "description": {
            "type": "string",
            "description": "Description of the analysis"
          },
          "experimentType": {
            "type": "string",
            "description": "Type of experiment",
            "enum": [
              "Whole genome sequencing",
              "Whole transcriptome sequencing",
              "Exome sequencing",
              "Genotyping by array",
              "Curation",
              "Genotyping by sequencing",
              "Target sequencing",
              "Transcriptomics"
            ]
          },
          "referenceGenome": {
            "type": "string",
            "description": "Reference against which the analysis was performed. ENA or NCBI accession (starting with GCA) accepted."
          },
          "evidenceType": {
            "type": "string",
            "description": "The type of evidence (allele frequencies or genotypes) provided in the VCF files of the analysis",
            "enum": [
              "genotype",
              "allele_frequency"
            ]
          },
          "referenceFasta": {
            "type": "string",
            "description": "The path to the reference in fasta format that was used to create the VCF. (This is a local path)"
          },
          "assemblyReport": {
            "type": "string",
            "description": "The path to the assembly report associated with the assembly as found in NCBI assemblies. (This is a local path and only applicable for GCAs)"
          },
          "platform": {
            "description": "Platform used to generate the raw data.",
            "type": "string",
            "examples": [
              "454 GS",
              "454 GS 20",
              "454 GS FLX",
              "454 GS FLX Titanium",
              "454 GS FLX+",
              "454 GS Junior",
              "AB 3130 Genetic Analyzer",
              "AB 3300 Genetic Analyzer",
              "AB 3730xl",
              "AB 5500 Genetic Analyzer",
              "AB 5500xl Genetic Analyzer",
              "AB SOLiD 3 Plus System",
              "AB SOLiD 4 System",
              "AB SOLiD 4hq System",
              "AB SOLiD PI System",
              "AB SOLiD System",
              "AB SOLiD System 2.0",
              "AB SOLiD System 3.0",
              "ABI 3500 Genetic Analyzer",
              "ABI PRISM 310 Genetic Analyzer",
              "Affymetrix",
              "BGISEQ-500",
              "Bio-Rad CFX96",
              "Complete Genomics",
              "Illumina",
              "Illumina CanineHD",
              "Illumina Genome Analyzer",
              "Illumina Genome Analyzer II",
              "Illumina Genome Analyzer IIx",
              "Illumina HiScanSQ",
              "Illumina HiSeq 1000",
              "Illumina HiSeq 2000",
              "Illumina HiSeq 2500",
              "Illumina HiSeq 3500",
              "Illumina HiSeq 4000",
              "Illumina HiSeq X Ten",
              "Illumina Hiseq Xten",
              "Illumina iScan",
              "Illumina MiniSeq",
              "Illumina MiSeq",
              "Illumina NextSeq 500",
              "Illumina NovaSeq 6000",
              "Ion Personal Genome Machine (PGM) System v2",
              "Ion S5XL",
              "Ion Torrent PGM",
              "Ion Torrent Proton",
              "MGISEQ-2000",
              "Nimblegen 4.2M Probe Custom DNA Microarray",
              "Oxford Nanopore PromethION",
              "unspecified"
            ]
          },
          "software": {
            "description": "Software used to generate the analysis.",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "pipelineDescriptions": {
            "type": "string"
          },
          "imputation": {
            "description": "Specify if imputation was used to generate the variants",
            "type": "boolean"
          },
          "phasing": {
            "description": "Specify if the variants have been phased",
            "type": "boolean"
          },
          "centre": {
            "description": "Centre, institute or company where the analysis was performed (if different from the project's centre).",
            "type": "string"
          },
          "date": {
            "description": "Date in which the analysis was performed",
            "type": "string"
          },
          "links": {
            "description": "Link(s) to external resources related to this analysis in the form DB:ID:LABEL.",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "runAccessions": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^(E|D|S)RR[0-9]{6,}$"
            },
            "description": "List of run accessions linking to the raw data used in this analysis if applicable (e.g. SRR576651, SRR576652)"
          }
        }
      }
    },
    "sample": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "if": {
          "required": [
            "bioSampleAccession"
          ]
        },
        "then": {
          "required": [
            "analysisAlias",
            "sampleInVCF",
            "bioSampleAccession"
          ]
        },
        "else": {
          "required": [
            "analysisAlias",
            "bioSampleObject"
          ]
        },
        "properties": {
          "analysisAlias": {
            "type": "array",
            "description": "Aliases of the analyses performed on this sample",
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "sampleInVCF": {
            "type": "string",
            "description": "Sample Name used in the VCF file. It is a required field when genotypes are provided."
          },
          "bioSampleAccession": {
            "type": "string",
            "pattern": "^SAM(E|D|N)[A-Z]?[0-9]+$",
            "description": "BioSample accession of pre-existing sample. Only use for preregistered samples"
          },
          "bioSampleObject": {
            "$ref": "https://www.ebi.ac.uk/biosamples/schema-store/registry/schemas/ERC000011"
          }
        }
      }
    },
    "files": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "analysisAlias",
          "fileName"
        ],
        "properties": {
          "analysisAlias": {
            "type": "string",
            "description": "Alias of the analysis that produced the file"
          },
          "fileName": {
            "type": "string",
            "description": "File name"
          },
          "fileSize": {
            "type": "number",
            "description": "Size of file in bytes"
          },
          "md5": {
            "type": "string",
            "description": "MD5 hash of the file"
          }
        }
      }
    }
  },
  "definitions": {
    "projectAccession": {
      "type": "string",
      "description": "ENA project accession",
      "pattern": "^PRJ(E|D|N)[A-Z][0-9]+$"
    }
  }
}

=== EBIvariation/eva-sub-cli/tests/resources/EVA_Submission_test_with_non_vcf_files.json
{
  "submitterDetails": [
    {
      "lastName": "Smith",
      "firstName": "John",
      "email": "john.smith@example.com",
      "laboratory": "Genomics Lab",
      "centre": "University of Example",
      "address": "1 street address"
    },
    {
      "lastName": "Doe",
      "firstName": "Jane",
      "email": "jane.doe@example.com",
      "laboratory": "Bioinformatics Lab",
      "centre": "University of Example",
      "address": "1 street address"
    }
  ],
  "project": {
    "title": "Example Project Title",
    "description": "An example project for demonstration purposes",
    "centre": "University of Example",
    "taxId": 9606,
    "holdDate": "2023-12-31T00:00:00"
  },
  "analysis": [
    {
      "analysisTitle": "Variant Detection 1",
      "analysisAlias": "VD1",
      "description": "An example analysis for demonstration purposes",
      "experimentType": "Whole genome sequencing",
      "referenceGenome": "GCA_000001405.27",
      "referenceFasta": "GCA_000001405.27_fasta.fa",
      "platform": "BGISEQ-500"
    },
    {
      "analysisTitle": "Variant Detection 2",
      "analysisAlias": "VD2",
      "description": "An example analysis for demonstration purposes",
      "experimentType": "Whole genome sequencing",
      "referenceGenome": "GCA_000001405.27",
      "referenceFasta": "GCA_000001405.27_fasta.fa",
      "platform": "BGISEQ-500"
    },
    {
      "analysisTitle": "Variant Detection 3",
      "analysisAlias": "VD3",
      "description": "An example analysis for demonstration purposes",
      "experimentType": "Whole genome sequencing",
      "referenceGenome": "GCA_000001405.27",
      "referenceFasta": "GCA_000001405.27_fasta.fa",
      "platform": "BGISEQ-500"
    }
  ],
  "sample": [
    {
      "analysisAlias": [
        "VD1",
        "VD2",
        "VD3"
      ],
      "sampleInVCF": "sample1",
      "bioSampleAccession": "SAME00001"
    },
    {
      "analysisAlias": [
        "VD1",
        "VD2",
        "VD3"
      ],
      "sampleInVCF": "sample2",
      "bioSampleAccession": "SAME00002"
    },
    {
      "analysisAlias": [
        "VD3"
      ],
      "sampleInVCF": "sample3",
      "bioSampleAccession": "SAME00003"
    },
    {
      "analysisAlias": [
        "VD4",
        "VD5"
      ],
      "sampleInVCF": "sample4",
      "bioSampleObject": {
        "name": "Lm_17_S8",
        "characteristics": {
          "title": [
            {
              "text": "Bastet normal sample"
            }
          ],
          "description": [
            {
              "text": "Test Description"
            }
          ],
          "taxId": [
            {
              "text": "9447"
            }
          ],
          "scientificName": [
            {
              "text": "Lemur catta"
            }
          ],
          "sex": [
            {
              "text": "Female"
            }
          ],
          "tissueType": [
            {
              "text": "skin"
            }
          ],
          "species": [
            {
              "text": "Lemur catta"
            }
          ]
        }
      }
    }
  ],
  "files": [
    {
      "analysisAlias": "VD1",
      "fileName": "example1.vcf.gz",
      "fileType": "vcf"
    },
    {
      "analysisAlias": "VD2",
      "fileName": "example2.vcf",
      "fileType": "vcf"
    },
    {
      "analysisAlias": "VD3",
      "fileName": "example3.vcf",
      "fileType": "vcf"
    },
    {
      "analysisAlias": "VD2",
      "fileName": "example2.vcf.gz.tbi",
      "fileType": "vcf"
    }
  ]
}

=== EBIvariation/eva-sub-cli/tests/resources/EVA_Submission_test_with_asm_report.json
{
  "submitterDetails": [
    {
      "lastName": "Smith",
      "firstName": "John",
      "telephone": "+1234567890",
      "email": "john.smith@example.com",
      "laboratory": "Genomics Lab",
      "centre": "University of Example",
      "address": "1 street address"
    },
    {
      "lastName": "Doe",
      "firstName": "Jane",
      "telephone": "+1234567890",
      "email": "jane.doe@example.com",
      "laboratory": "Bioinformatics Lab",
      "centre": "University of Example",
      "address": "1 street address"
    }
  ],
  "project": {
    "title": "Example Project Title",
    "projectAlias": "EP",
    "description": "An example project for demonstration purposes",
    "centre": "University of Example",
    "taxId": 9606,
    "holdDate": "2023-12-31T00:00:00"
  },
  "analysis": [
    {
      "analysisTitle": "Variant Detection 1",
      "analysisAlias": "VD1",
      "description": "An example analysis for demonstration purposes",
      "ProjectTitle": "Example Project",
      "experimentType": "Whole genome sequencing",
      "referenceGenome": "GCA_000001405.27",
      "referenceFasta": "GCA_000001405.27_fasta.fa",
      "assemblyReport": "GCA_000001405.27_report.txt",
      "platform": "BGISEQ-500"
    },
    {
      "analysisTitle": "Variant Detection 2",
      "analysisAlias": "VD2",
      "description": "An example analysis for demonstration purposes",
      "ProjectTitle": "Example Project",
      "experimentType": "Whole genome sequencing",
      "referenceGenome": "GCA_000001405.27",
      "referenceFasta": "GCA_000001405.27_fasta.fa",
      "assemblyReport": "GCA_000001405.27_report.txt",
      "platform": "BGISEQ-500"
    },
    {
      "analysisTitle": "Variant Detection 3",
      "analysisAlias": "VD3",
      "description": "An example analysis for demonstration purposes",
      "ProjectTitle": "Example Project",
      "experimentType": "Whole genome sequencing",
      "referenceGenome": "GCA_000001405.27",
      "referenceFasta": "GCA_000001405.27_fasta.fa",
      "assemblyReport": "GCA_000001405.27_report.txt",
      "platform": "BGISEQ-500"
    }
  ],
  "sample": [
    {
      "analysisAlias": [
        "VD1",
        "VD2",
        "VD3"
      ],
      "sampleInVCF": "sample1",
      "bioSampleAccession": "SAME00001"
    },
    {
      "analysisAlias": [
        "VD1",
        "VD2",
        "VD3"
      ],
      "sampleInVCF": "sample2",
      "bioSampleAccession": "SAME00002"
    },
    {
      "analysisAlias": [
        "VD3"
      ],
      "sampleInVCF": "sample3",
      "bioSampleAccession": "SAME00003"
    },
    {
      "analysisAlias": [
        "VD4",
        "VD5"
      ],
      "sampleInVCF": "sample4",
      "bioSampleObject": {
        "name": "Lm_17_S8",
        "characteristics": {
          "title": [
            {
              "text": "Bastet normal sample"
            }
          ],
          "description": [
            {
              "text": "Test Description"
            }
          ],
          "taxId": [
            {
              "text": "9447"
            }
          ],
          "scientificName": [
            {
              "text": "Lemur catta"
            }
          ],
          "sex": [
            {
              "text": "Female"
            }
          ],
          "tissueType": [
            {
              "text": "skin"
            }
          ],
          "species": [
            {
              "text": "Lemur catta"
            }
          ]
        }
      }
    }
  ],
  "files": [
    {
      "analysisAlias": "VD1",
      "fileName": "example1.vcf.gz",
      "fileType": "vcf"
    },
    {
      "analysisAlias": "VD2",
      "fileName": "example2.vcf",
      "fileType": "vcf"
    },
    {
      "analysisAlias": "VD3",
      "fileName": "example3.vcf",
      "fileType": "vcf"
    }
  ]
}
